POST http://127.0.0.1:8000/login/ Content-Type: application/json

{ "username": "amira", "password": "0000" } ####

POST http://127.0.0.1:8000/signup/ Content-Type: application/json

{ "username": "laila", "password": "ll665:&066", "email": "laila@email.co" } ####

GET http://127.0.0.1:8000/test_token Content-Type: application/json Authorization: Token cc0e07ca502c08cf94b7cede936fe4aa6c63de68

{}