# Generated by Django 4.1.13 on 2024-04-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('field2', models.IntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('major', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'my_collection',
                'managed': False,
            },
        ),
    ]
