# Generated by Django 5.0.4 on 2024-05-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SessionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CaptureTime", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "SessionEndedAt",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "SessionStartedAt",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("Session_for", models.CharField(default="", max_length=255)),
                ("arousal", models.IntegerField()),
                ("attention", models.IntegerField()),
                ("dominantEmotion", models.CharField(max_length=50)),
                ("userEmail", models.CharField(max_length=100)),
                ("valence", models.FloatField()),
                ("volume", models.FloatField()),
            ],
        ),
    ]
