# Generated by Django 4.1.13 on 2024-04-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='morph_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('arousal', models.SmallIntegerField(default='')),
                ('attention', models.IntegerField(default='')),
                ('valence', models.FloatField(default='')),
                ('volume', models.FloatField(default='')),
                ('dominantEmotion', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
