# Generated by Django 5.0.4 on 2024-05-13 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_sessiondata_session_for"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessiondata",
            name="feature_1",
        ),
        migrations.RemoveField(
            model_name="sessiondata",
            name="feature_2",
        ),
        migrations.RemoveField(
            model_name="sessiondata",
            name="feature_3",
        ),
        migrations.RemoveField(
            model_name="sessiondata",
            name="feature_4",
        ),
        migrations.RemoveField(
            model_name="sessiondata",
            name="feature_5",
        ),
        migrations.RemoveField(
            model_name="sessiondata",
            name="gender",
        ),
    ]
