# Generated by Django 5.0.4 on 2024-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_sessiondata_arousal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiondata",
            name="arousal",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="attention",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="dominantEmotion",
            field=models.CharField(
                blank=True, default="Neutral", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="userEmail",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="valence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="volume",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
