# Generated by Django 5.0.4 on 2024-05-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_sessiondata_arousal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessiondata",
            name="arousal",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sessiondata",
            name="attention",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
